tls_server_config:
  cert_file: /opt/bitnami/prometheus/conf/prometheus.crt
  key_file: /opt/bitnami/prometheus/conf/prometheus.key
  client_ca_file: /opt/bitnami/prometheus/conf/ca.crt
  client_auth_type: RequireAndVerifyClientCert

basic_auth_users:
  prometheus: $2b$12$hNf2lSsxfm0.i4a.1kVpSOVyBCfIB51VRjgBUyv6kdnyTlgWj81Ay
